import os

from config import Config


class TestConfig(Config):
    # Test db
    SQLALCHEMY_DATABASE_URI = os.environ.get(
        'TEST_DATABASE_URL', 'sqlite:///test.db?check_same_thread=False'
    )

    # Test Image directory
    IMG_UPLOAD_DIR = '/static/img/uploads/test'

    # Suppress mail sending
    MAIL_SUPPRESS_SEND = True

    # Invalid token generated by unknown source for testing.
    EXAMPLE_INVALID_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ' \
                            '9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ikpv' \
                            'aG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwR' \
                            'JSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'

    # Valid expired token.
    EXPIRED_TOKEN = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOj' \
                    'E1ODk4MjY0MzgsImlhdCI6MTU4OTgyNTgzOCwic3ViIjoiMjgiLCJ' \
                    'wZXJtaXNzaW9ucyI6WyJtYW5hZ2U6c2VsZiJdLCJyYW5kIjoiMDdmM' \
                    'jM5MzgifQ.7Apufb7OFATuN13T0EhvqRBuFAQW7yO9p781lPbQXnM'
