from config import Config


class TestConfig(Config):
    # Test db
    SQLALCHEMY_DATABASE_URI = 'sqlite:///test.db?check_same_thread=False'

    # Test Image directory
    IMG_UPLOAD_DIR = 'static/img/uploads/test'

    # Invalid token generated by unknown source for testing.
    EXAMPLE_INVALID_TOKEN = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ' \
                            '9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ikpv' \
                            'aG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwR' \
                            'JSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'

    # Valid token generated by Auth0 but has expired.
    EXAMPLE_TOKEN = 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHA' \
                    'iOjE1ODk3MjE1OTAsImlhdCI6MTU4OTcyMTU4MCwic3ViIjoxL' \
                    'CJwZXJtaXNzaW9ucyI6WyJtYW5hZ2U6NjM0NCIsIm1hbmFnZTo' \
                    '5MDA0Il0sInJhbmQiOiI3ZjQyODA4YSJ9.0Ko6tOZO1_RRi7C' \
                    'VPtEg0XRpBtFbzGRK7PGwcSMe2kQ'

    # Valid token generated by Auth0 for user without any assigned role.
    #
    # This token has expired but can be used to check invalid permissions by
    # bypassing token verification while testing.
    NO_PERMISSION_TOKEN = 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZC' \
                          'I6IllhT3RnLWR4WmJMRmZOUnlOQkVEbSJ9.eyJpc3MiOiJodHR' \
                          'wczovL2xpbXZ1cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8N' \
                          'WU5ZjFmZmY2YWZhY2IwY2JiMTBiYTJjIiwiYXVkIjoiY29mZmV' \
                          'lLXNob3AtYXV0aCIsImlhdCI6MTU4NzQ4NjcyNCwiZXhwIjox' \
                          'NTg3NDkzOTI0LCJhenAiOiJ4UzlBUnlldU1qYm5UbU1xMkJQVk' \
                          'lab1BqNlVjQzY2dyIsInNjb3BlIjoiIiwicGVybWlzc2lvbnM' \
                          'iOltdfQ.IGGCeX9-O3P2B4_VYC_OIWacJO5jnW5XLFilHN7DV' \
                          '8h0nElD6ah0dSxnHse1FkO4G2iNV8S3kXuR5dlX95Um9ncfzG' \
                          'IpJF9rf9tQTbW6ODRFHh6s-r2Zr8mvVwoTyfVYj2szyTpxbBk' \
                          '9P4LkRAJNlTRA74xfe1jnUfDnlQGODaa2tPCrkH5tavrNN-om' \
                          'QJjeR-UIjnUseOg-TGdNL5keCsz5tCxbon1MLT1WSSqx_YtCR' \
                          'BZHkZc-H0KU5Fz9WwWEfLolCE7taLeLgTlDNCjotf6ii' \
                          'b2zNfGX8d_vp4yN7QD4r4esk0khk1j2Hl4BVuq9XZr8FSM0' \
                          'yUP88_ZhQ28iMw'
