"""empty message

Revision ID: de5773d63192
Revises: 1de68ccf199a
Create Date: 2020-05-13 19:03:05.668464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de5773d63192'
down_revision = '1de68ccf199a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_image',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('post_id', 'image_id')
    )
    op.drop_column('image', 'created_at')
    op.drop_column('image', 'model_id')
    op.drop_column('image', 'model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('model', postgresql.ENUM('post', 'comment', 'chat', 'user', 'profile', name='model'), autoincrement=False, nullable=False))
    op.add_column('image', sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('image', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_table('post_image')
    # ### end Alembic commands ###
