"""empty message

Revision ID: df859aa48ec6
Revises: de5773d63192
Create Date: 2020-05-14 17:59:12.623272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df859aa48ec6'
down_revision = 'de5773d63192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('activity', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.drop_column('activity', 'created_at')
    op.drop_column('activity', 'updated_at')
    op.add_column('comment', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('comment', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.drop_column('comment', 'created_at')
    op.drop_column('comment', 'updated_at')
    op.add_column('post', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('react', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('react', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'react', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'react', type_='foreignkey')
    op.drop_column('react', 'updated_on')
    op.drop_column('react', 'created_on')
    op.drop_column('post', 'updated_on')
    op.drop_column('post', 'created_on')
    op.add_column('comment', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('comment', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'updated_on')
    op.drop_column('comment', 'created_on')
    op.add_column('activity', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('activity', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('activity', 'updated_on')
    op.drop_column('activity', 'created_on')
    # ### end Alembic commands ###
