import os


class Config:
    # Enable debug mode
    DEBUG = True

    # App secret
    # SECRET_KEY = os.environ.get('SECRET_KEY')
    SECRET_KEY = 'my_test_secret_key'

    # Configure SQLAlchemy and database
    # SQLALCHEMY_DATABASE_URI = os.environ.get('SQLALCHEMY_DATABASE_URI')
    SQLALCHEMY_DATABASE_URI = "postgres://postgres:password@localhost:5432/limbook_api_test"
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_ECHO = True

    # Auth0 credentials
    AUTH0_DOMAIN = 'limvus.auth0.com'
    ALGORITHMS = ['RS256']
    API_AUDIENCE = 'limbook-auth-api'

    # Invalid token generated by unknown source for testing.
    EXAMPLE_INVALID_TOKEN = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ' \
                            '9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ikpv' \
                            'aG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwR' \
                            'JSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'

    # Valid token generated by Auth0 but has expired.
    EXAMPLE_TOKEN = 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6I' \
                    'llhT3RnLWR4WmJMRmZOUnlOQkVEbSJ9.eyJpc3MiOiJodHRwczovL' \
                    '2xpbXZ1cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWViNjZhMm' \
                    'QxY2MxYWMwYzE0OTZjMTZmIiwiYXVkIjoibGltYm9vay1hdXRoLW' \
                    'FwaSIsImlhdCI6MTU4OTA0MTIzMiwiZXhwIjoxNTg5MDQ4NDMyL' \
                    'CJhenAiOiJldzcyR3p2bzU4SWJsYkVjYmRMTXFBMXY3Rk03YTV' \
                    'SWiIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiY3JlYXRlOm' \
                    'NoYXRfbWVzc2FnZXMiLCJjcmVhdGU6Y29tbWVudHMiLCJjcmVhdGU' \
                    '6cG9zdHMiLCJDcmVhdGU6cmVhY3RzIiwiZGVsZXRlOmNoYXRfbWV' \
                    'zc2FnZXMiLCJkZWxldGU6Y29tbWVudHMiLCJkZWxldGU6cG9zdHM' \
                    'iLCJkZWxldGU6cmVhY3RzIiwicmVhZDpjaGF0X21lc3NhZ2VzIiw' \
                    'icmVhZDpjb21tZW50cyIsInJlYWQ6cG9zdHMiLCJyZWFkOnJlYWN' \
                    '0cyIsInVwZGF0ZTpjb21tZW50cyIsInVwZGF0ZTpwb3N0cyIsInV' \
                    'wZGF0ZTpyZWFjdHMiXX0.AaKaHw_Ys5xdhqdTLUX-IltaXYRQMOk' \
                    '57UjCTKwtmGUX0dcziq3S99ea8cUMo0t7ZSGwR6CyCIrJfTS3mee' \
                    'SMQOZ3Glv9QML3BKybA4ZF54HqBOgp54Ws7gB01_L5rHTFzYhE7o' \
                    'o-uXZxKKKbn7bRFKM7aoW6ErTbVtMARRbduHRZlj5HiH2u9cEMff' \
                    'sxdtxRVPiFi3Ufn5r_F2oAWlO7g5h80Gyaxc_86i7IumzFTvQbKo' \
                    'Y1TCbyHdnHzuNroTDPmEtlJh0TQ-zg1AZsnJhFiXJeWdGuqVk13' \
                    'YSyuaxNm7zaKihzxIBwY63FPO5TNWBc36clgXeHT2onnBjl-wZIw'

    # Valid token generated by Auth0 for user without any assigned role.
    #
    # This token has expired but can be used to check invalid permissions by
    # bypassing token verification while testing.
    NO_PERMISSION_TOKEN = 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZC' \
                          'I6IllhT3RnLWR4WmJMRmZOUnlOQkVEbSJ9.eyJpc3MiOiJodHR' \
                          'wczovL2xpbXZ1cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8N' \
                          'WU5ZjFmZmY2YWZhY2IwY2JiMTBiYTJjIiwiYXVkIjoiY29mZmV' \
                          'lLXNob3AtYXV0aCIsImlhdCI6MTU4NzQ4NjcyNCwiZXhwIjox' \
                          'NTg3NDkzOTI0LCJhenAiOiJ4UzlBUnlldU1qYm5UbU1xMkJQVk' \
                          'lab1BqNlVjQzY2dyIsInNjb3BlIjoiIiwicGVybWlzc2lvbnM' \
                          'iOltdfQ.IGGCeX9-O3P2B4_VYC_OIWacJO5jnW5XLFilHN7DV' \
                          '8h0nElD6ah0dSxnHse1FkO4G2iNV8S3kXuR5dlX95Um9ncfzG' \
                          'IpJF9rf9tQTbW6ODRFHh6s-r2Zr8mvVwoTyfVYj2szyTpxbBk' \
                          '9P4LkRAJNlTRA74xfe1jnUfDnlQGODaa2tPCrkH5tavrNN-om' \
                          'QJjeR-UIjnUseOg-TGdNL5keCsz5tCxbon1MLT1WSSqx_YtCR' \
                          'BZHkZc-H0KU5Fz9WwWEfLolCE7taLeLgTlDNCjotf6ii' \
                          'b2zNfGX8d_vp4yN7QD4r4esk0khk1j2Hl4BVuq9XZr8FSM0' \
                          'yUP88_ZhQ28iMw'
