  name: limbook-api-ci

  on:
    push:
      branches:
        - develop
        - master
    pull_request:
      branches:
        - develop
        - master

  jobs:
    build-and-test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [3.7, 3.x]
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SQLALCHEMY_DATABASE_URI: ${{ secrets.DATABASE_URL }}
        REDIS_URL: ${{ secrets.REDIS_URL }}
        MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
        MAIL_PORT: ${{ secrets.MAIL_PORT }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

      name: Python ${{ matrix.python-version }}
      steps:
        - uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
            architecture: x64

        - name: Install dependencies
          run: |
            pip install -r requirements.txt

        - name: Run tests
          run: |
            pytest