  name: limbook-api-ci
    description: CI for limbook api

  on:
    push:
      - master
      - develop
    pull_request:
      - develop
      - master

  jobs:
    build-and-test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ['3.x']
      name: Python ${{ matrix.python-version }}
      steps:
        - uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
            architecture: x64
        - name: Install dependencies
          run: |
            pip install -r requirements.txt
        - name: Run tests
          run: |
            python -m unittest tests/*test.py
